name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run install
        run: yarn install

      - name: Test
        run: yarn test
